services:
  db:
    image: postgres:latest
    container_name: Projet_BDD
    restart: always
    environment:
      POSTGRES_USER: Julien
      POSTGRES_PASSWORD: Azerty1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh